version: '3'

services:
  zookeeper1:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka1:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "usuarios:1:3"
